version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8848:8848"
    environment:
      - NODE_ENV=development
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=3000
      - CHOKIDAR_USEPOLLING=true 