version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8848:8848"
    environment:
      - NODE_ENV=development
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=8848
      - CHOKIDAR_USEPOLLING=true

  # 添加一个专门用于运行命令的服务，如添加依赖等
  pnpm:
    image: node:latest
    volumes:
      - .:/app
      - pnpm_cache:/root/.pnpm-store
    working_dir: /app
    # 先安装pnpm，然后使用pnpm作为入口命令
    entrypoint: ["/bin/sh", "-c", "npm install -g pnpm && pnpm $0 $@"]
    profiles:
      - tools

  # 添加Supabase CLI服务
  supabase-cli:
    image: docker.mybacc.com/michaeltaylor3d/supabase-cli:latest
    volumes:
      - .:/workdir
    working_dir: /workdir
    environment:
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN:-}
    # 使容器保持运行，但不消耗资源
    command: tail -f /dev/null
    # 共享宿主网络以便访问本地数据库
    network_mode: "host"

volumes:
  pnpm_cache:
    name: pnpm-cache
